name: DEV - Deploy Ubuntu

on:
  push:
    branches:
      - dev-app

jobs:
  deploy-dev:
    runs-on: [self-hosted, ubuntu-dev]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar rsync
        run: |
          sudo apt update -y
          sudo apt install -y rsync

      - name: Copiar archivos al entorno DEV (Ubuntu Proxmox)
        run: |
          SOURCE="$GITHUB_WORKSPACE"
          TARGET="/var/www/html/proyecto-ubuntu-dev"

          sudo mkdir -p "$TARGET"
          sudo rsync -av --delete "$SOURCE"/ "$TARGET"/
