name: DEV - Deploy Ubuntu

on:
  push:
    branches:
      - dev-app

jobs:
  deploy-dev:
    runs-on: [self-hosted, dev]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # rsync ya está instalado en el servidor, no uses sudo aquí

      - name: Copiar archivos al entorno DEV (Ubuntu Proxmox)
        run: |
          SOURCE="$GITHUB_WORKSPACE"
          TARGET="/var/www/html/proyecto-ubuntu-dev"
          mkdir -p "$TARGET"
          rsync -av --delete "$SOURCE"/ "$TARGET"/
