name: DEV - Deploy Ubuntu

on:
  push:
    branches:
      - dev-app

jobs:
  deploy-dev:
    runs-on: [self-hosted, dev]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to DEV (Ubuntu Proxmox)
        run: |
          TARGET="/var/www/html/proyecto-ubuntu-dev"
          mkdir -p "$TARGET"
          rsync -av --delete ./ "$TARGET"/
